[package]
name = "zview"
version = "0.1.0"
edition = "2024"

[dependencies]
cgmath = { version = "0.18.0", features = ["swizzle"] }
hjkl-clipboard = "0.33.2"
image = { version = "0.25.10", features = ["avif", "avif-native", "default-formats"] }
sdl3 = "0.18.4"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
